### ISSUE TITLE
gray out times/spots on reserve page that are unavailable

### ISSUE THREAD

**Issue by martinn8145** [cmtnguyen/CS160-project#20]
You can still reserve spots that have already been reserved, so we needa gray ou those ones. I just used uuid as a placeholder for reservation id, but maybe we can make it something like time + spot + name, and then you can just check the time and spot on the reserve page before graying out the unavailable ones.

**Comment by jonathanSeang** [comment]
Just finished implementing on branch "disable-unavailable-reservations". Comments would be appreciated.
